// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TE_assignment_2025.Dal;

#nullable disable

namespace TE_assignment_2025.Migrations
{
    [DbContext(typeof(TEAssignmentDBContext))]
    partial class TEAssignmentDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TE_assignment_2025.Model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NoOfMembers")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TE_assignment_2025.Model.ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");
                });

            modelBuilder.Entity("TE_assignment_2025.Model.Skills", b =>
                {
                    b.Property<int>("SkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SkillsId"));

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SkillsId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillsId = 1,
                            SkillName = "Asp.Net"
                        },
                        new
                        {
                            SkillsId = 2,
                            SkillName = "Java"
                        },
                        new
                        {
                            SkillsId = 3,
                            SkillName = "PHP"
                        },
                        new
                        {
                            SkillsId = 4,
                            SkillName = "Python"
                        },
                        new
                        {
                            SkillsId = 5,
                            SkillName = "React-js"
                        },
                        new
                        {
                            SkillsId = 6,
                            SkillName = "Web-Java"
                        },
                        new
                        {
                            SkillsId = 7,
                            SkillName = "Node-js"
                        },
                        new
                        {
                            SkillsId = 8,
                            SkillName = "MySQL"
                        },
                        new
                        {
                            SkillsId = 9,
                            SkillName = "Flutter"
                        },
                        new
                        {
                            SkillsId = 10,
                            SkillName = "CSharp"
                        },
                        new
                        {
                            SkillsId = 11,
                            SkillName = "HTML"
                        },
                        new
                        {
                            SkillsId = 12,
                            SkillName = "CSS"
                        },
                        new
                        {
                            SkillsId = 13,
                            SkillName = "javaScript/Jquery"
                        },
                        new
                        {
                            SkillsId = 14,
                            SkillName = "MongoDB"
                        },
                        new
                        {
                            SkillsId = 15,
                            SkillName = "Asp.Net-core"
                        },
                        new
                        {
                            SkillsId = 16,
                            SkillName = "Next-js"
                        });
                });

            modelBuilder.Entity("TE_assignment_2025.Model.ProjectSkill", b =>
                {
                    b.HasOne("TE_assignment_2025.Model.Project", "project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TE_assignment_2025.Model.Skills", "skills")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("skills");
                });

            modelBuilder.Entity("TE_assignment_2025.Model.Project", b =>
                {
                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("TE_assignment_2025.Model.Skills", b =>
                {
                    b.Navigation("ProjectSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
